name = "task-manager"
version = "0.1.0"
component = "/Users/colinrozzi/work/actor-registry/task-manager/./target/wasm32-unknown-unknown/release/task_manager.wasm"

[permission_policy.message_server]
type = "inherit"

[permission_policy.file_system]
type = "inherit"

[permission_policy.http_client]
type = "inherit"

[permission_policy.http_framework]
type = "inherit"

[permission_policy.runtime]
type = "inherit"

[permission_policy.supervisor]
type = "inherit"

[permission_policy.store]
type = "inherit"

[permission_policy.timing]
type = "inherit"

[permission_policy.process]
type = "inherit"

[permission_policy.environment]
type = "inherit"

[permission_policy.random]
type = "inherit"

[[handlers]]
type = "message-server"

[handlers.config]

[[handlers]]
type = "runtime"

[handlers.config]

[[handlers]]
type = "supervisor"

[handlers.config]

[[handlers]]
type = "random"

[handlers.config]
max_bytes = 1048576
max_int = 9223372036854775807
allow_crypto_secure = false
