name = "task-manager"
version = "0.1.0"
component = "/Users/colinrozzi/work/actor-registry/task-manager/./target/wasm32-unknown-unknown/release/task_manager.wasm"
save_chain = true

[[handler]]
type = "message-server"

[[handler]]
type = "runtime"

[[handler]]
type = "supervisor"

[[handler]]
type = "random"
max_bytes = 1048576
max_int = 9223372036854775807
allow_crypto_secure = false
